### PR TITLE
Update freetype.

### PR DESCRIPTION
**Pull request by emilio**
r? @jdm (or anyone else)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-azure/253)

### CODE REVIEW

**Comment by jdm** [comment]
We probably need to fix Travis unless we merge manually.

**Comment by emilio** [comment]
Gah, that's annoying, will see if I can address it.

**Comment by emilio** [comment]
Traced this down to a change in x11's build that now require a newer version, opened https://github.com/Daggerbot/x11-rs/issues/57

**Comment by emilio** [comment]
I guess it's fine to merge manually until that's fixed given this is a pretty unrelated change?

**Comment by emilio** [comment]
(I can also downgrade x11, of course, but then we need to re-upgrade it).

**Comment by jdm** [comment]
I would rather have a successful build than merge blindly, given that freetype 0.1.3 continues to work (as demonstrated in the other PR that merged).

**Comment by emilio** [comment]
@jdm The other PR merged without a new build.

@bors-servo try

**Comment by emilio** [comment]
Doing a try run because of https://github.com/Daggerbot/x11-rs/issues/57#issuecomment-272717581

**Comment by emilio** [comment]
There you go, r? @jdm

**Pull request merged**
