### PR TITLE
Add Path::IsPointInPath and Path::CopyToPathBuilder

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/rust-azure/208)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/rust-azure/208#-:-K4L2MDjeuP0VWGFcGCS:1236647940)*

**Comment by jdm** [comment]
https://github.com/servo/rust-layers/issues/217

**Comment by frewsxcv** [comment]
servo/rust-layers#217 has been resolved

**Pull request merged**
