### PR TITLE
Update to libc 0.2.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/rust-azure/206)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/rust-azure/206#-:-K49m3VASCGQ-VelVO5n:1236647940)*

**Comment by jdm** [comment]
```
$ cargo build --verbose

    Updating registry `https://github.com/rust-lang/crates.io-index`

    Updating git repository `https://github.com/servo/skia`

    Updating git repository `https://github.com/servo/libfreetype2`

    Updating git repository `https://github.com/servo/rust-freetype`

Unable to update https://github.com/servo/rust-freetype

Caused by:

  failed to clone into: /home/travis/.cargo/git/db/rust-freetype-94fb97121b442a27

Caused by:

  [2/-1] Failed to connect to github.com: Connection timed out

2.79s$ cargo test --verbose

    Updating registry `https://github.com/rust-lang/crates.io-index`

    Updating git repository `https://github.com/servo/skia`

    Updating git repository `https://github.com/servo/rust-freetype`

    Updating git repository `https://github.com/servo/libfreetype2`

    Updating git repository `https://github.com/servo/rust-egl`

    Updating git repository `https://github.com/servo/core-text-rs`

no matching package named `skia` found (required by `azure`)

location searched: https://github.com/servo/skia

version required: *

The command "cargo test --verbose" exited with 101.
```

**Comment by jdm** [comment]
```
95.43s$ cargo build --verbose

    Updating registry `https://github.com/rust-lang/crates.io-index`

    Updating git repository `https://github.com/servo/skia`

    Updating git repository `https://github.com/servo/rust-egl`

    Updating git repository `https://github.com/servo/libfreetype2`

    Updating git repository `https://github.com/servo/rust-freetype`

    Updating git repository `https://github.com/servo/core-text-rs`

no matching package named `skia` found (required by `azure`)

location searched: https://github.com/servo/skia

version required: *
```
https://github.com/servo/skia/blob/master/Cargo.toml#L3

**Comment by jdm** [comment]
Ah: https://github.com/servo/skia/issues/70#issuecomment-160185030

**Pull request closed without merging**
