### PR TITLE
Make the Skia GL backend opt-out.

### PR DESCRIPTION
**Pull request by jdm**
Servo doesn't actually use the GL support and it makes it harder to build for non-GL platforms.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-azure/300)

### CODE REVIEW

**Comment by jdm** [comment]
Depends on https://github.com/servo/skia/pull/177.

**Comment by paulrouget** [comment]
This compiles. But when compiling servo with this version of azure (with no default features), I'm getting linking errors, like:

```
  = note: lld-link.exe: error: undefined symbol: ?CreateFromName@SkTypeface@@SAPEAV1@QEBDW4Style@1@@Z
          >>> referenced by c:\msys64\home\paul\git\rust-azure\libazure\scaledfontskia.cpp:44
          >>>               libazure-4b9413b847428edf.rlib(ScaledFontSkia.obj):($LN40)


          lld-link.exe: error: undefined symbol: ?CreateFromStream@SkTypeface@@SAPEAV1@PEAVSkStream@@@Z
          >>> referenced by c:\msys64\home\paul\git\rust-azure\libazure\scaledfontskia.cpp:51
          >>>               libazure-4b9413b847428edf.rlib(ScaledFontSkia.obj):($LN7)

```

**Comment by jdm** [comment]
@paulrouget See if the situation is improved with the latest changes from both rust-azure and skia PRs.

**Comment by paulrouget** [comment]
Most of errors are. Left with:

```
  = note: lld-link.exe: error: undefined symbol: __imp_wglGetCurrentContext
          >>> referenced by libskia-62261fbc6ffb37af.rlib(GrGLCreateNativeInterface_win.obj):($LN25)


          lld-link.exe: error: undefined symbol: __imp_wglGetProcAddress
          >>> referenced by libskia-62261fbc6ffb37af.rlib(GrGLCreateNativeInterface_win.obj):(?win_get_gl_proc@@YAP6AXXZPEAXQEBD@Z)
```

**Pull request closed without merging**
