### PR TITLE
Add support for surface pattern.

### PR DESCRIPTION
**Pull request by hyowon**
I'm interested in implementing canvas features for servo.
SurfacePattern seems to be needed to support pattern fill for canvas.

### CODE REVIEW

**Comment by pcwalton** [comment]
This will also be useful for making our tiled background painting code less hilariously slow.

**Comment by hyowon** [comment]
@jdm All patterns are cloneable now.

#[derive(Clone)]
pub enum Pattern {
    Color(ColorPattern),
    LinearGradient(LinearGradientPattern),
    RadialGradient(RadialGradientPattern),
    Surface(SurfacePattern),
}

I'm not sure whether we can remove clone from all patterns or not.
But CanvasPaintState having Patterns needs clone.

#[derive(Clone)]
struct CanvasPaintState<'a> {
    draw_options: DrawOptions,
    fill_style: Pattern,
    stroke_style: Pattern,
    stroke_opts: StrokeOptions<'a>,
    /// The current 2D transform matrix.
    transform: Matrix2D<f32>,
}

Is it difficult to keep on using clone while avoiding a dangling pointer?
I'm a newbie to rust and servo. Please advice me further. Thank you for your review.

@pcwalton Interesting. I'll also see the tiled background painting code.

**Comment by jdm** [comment]
Yeah, I just noticed that the other pattern types derive Clone as well, so they have the same problem. The way to fix it here is to add a C API to clone an AzSurfacePatternRef that casts it to `gfx::SourcePattern` and returns `new SurfacePattern(sourcePattern->mSurface, sourcePattern->mExtendMode, sourcePatter->mFilter, sourcePattern->mMatrix, sourcePattern->mSamplingRect)`. We should do the same for the other pattern types, and manually implement the `Clone` trait instead of deriving it. Does that make sense?

**Comment by hyowon** [comment]
That makes great sense. Thank you for your kind guidance. Please review additional patch.

**Comment by jdm** [comment]
Looks great!

**Comment by hyowon** [comment]
cc @yichoi

**Pull request merged**
