### PR TITLE
[msvc] Build rust-azure using cmake for msvc compat

### PR DESCRIPTION
**Pull request by vvuk**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-azure/228)

### CODE REVIEW

**Comment by metajack** [comment]
Some comments and probably this should be squashed, but it looks close. I suspect without fixing the TODO, we will regress android performance substantially.

---

Reviewed 3 of 3 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[CMakeLists.txt, line 60 \[r5\]](https://reviewable.io:443/reviews/servo/rust-azure/228#-KMRCaYnR3Y9NXMX0vvR:-KMRCaYnR3Y9NXMX0vvS:-1713461004) ([raw file](https://github.com/servo/rust-azure/blob/73287e84984aa290f0119c962ba2ffad43dc3f8c/CMakeLists.txt#L60)):*
> ```CMake
>   include_directories($ENV{DEP_FREETYPE_OUTDIR}/include)
> else()
>   # We need to work with older pkg-config
> ```

I'm not sure what this comment means. Can you describe why pkg_check_modules is insufficient?

---

*[CMakeLists.txt, line 128 \[r5\]](https://reviewable.io:443/reviews/servo/rust-azure/228#-KMRCnlRP66t3J5auxC6:-KMRCnlRP66t3J5auxC7:-634971979) ([raw file](https://github.com/servo/rust-azure/blob/73287e84984aa290f0119c962ba2ffad43dc3f8c/CMakeLists.txt#L128)):*
> ```CMake
>   
>   if (CMAKE_COMPILER_IS_GNUCC)
>     # we could use pkg-config here, probably
> ```

Does the previous EXEC_PROGRAM bit already set cflags? So it should get the right header path. THat should leave only -DMOZ_ENABLE_FREETYPE right?

---

*[CMakeLists.txt, line 202 \[r5\]](https://reviewable.io:443/reviews/servo/rust-azure/228#-KMRCxjY4xsX4JJGXtVd:-KMRCxjY4xsX4JJGXtVe:-1577729287) ([raw file](https://github.com/servo/rust-azure/blob/73287e84984aa290f0119c962ba2ffad43dc3f8c/CMakeLists.txt#L202)):*
> ```CMake
> if("$ENV{DEP_FREETYPE_OUTDIR}" STREQUAL "")
>   include_directories($ENV{DEP_FREETYPE_OUTDIR}/include)
>   EXEC_PROGRAM(pkg-config ARGS --libs freetype2 OUTPUT_VARIABLE FREETYPE_CLDFLAGS)
> ```

Same question here about why the builtin package stuff isn't sufficient.

---

*[libazure/2D.h, line 1221 \[r2\]](https://reviewable.io:443/reviews/servo/rust-azure/228#-KMRAjRKkmLDY2g7ACe0:-KMRAjRLabKDdoFygGU6:1134857168) ([raw file](https://github.com/servo/rust-azure/blob/b33811289764718eaf452a78b6fce7d089af1a8c/libazure/2D.h#L1221)):*
> ```objc
> #endif
> 
> #if defined(WIN32) && !defined(MOZ_DISABLE_D2D_D3D)
> ```

Why are we disabling D2D & D3d?

Are you also upstreaming this change or does such a change already exist upstream?

---

*[src/azure-c.cpp, line 529 \[r4\]](https://reviewable.io:443/reviews/servo/rust-azure/228#-KMRCV1fPjYSvUfHaDwV:-KMRCV1g3c4D4rMBPHpK:820006209) ([raw file](https://github.com/servo/rust-azure/blob/395ad3aa0caa99d1349f0cfa01fc0cf68d9738d5/src/azure-c.cpp#L529)):*
> ```cpp
>         case gfx::SurfaceFormat::UNKNOWN:
>             return AZ_FORMAT_UNKNOWN;
>         default:
> ```

Why is this needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-azure/228#-:-KMRD7VNiHjLgRepB1QC:167895152)*

**Comment by vvuk** [comment]
I didn't do as good a job at cleaning this up; sorry about that.  It's clean now, and resolves all of your questions --

The older pkg-config comment should have read "older cmake".  The TODOs were for Skia (I copied that block from there) and are fixed there, though I need to get rid of the TODO comment.  The disable D2D/D3D stuff isn't needed (was an include paths issue).  And the default assert thing was needed at one point when we were trying to build with -Wall -Werror, but that's not going to work for azure :)

**Comment by metajack** [comment]
Reviewed 4 of 4 files at r6.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[CMakeLists.txt, line 60 \[r5\]](https://reviewable.io:443/reviews/servo/rust-azure/228#-KMRCaYnR3Y9NXMX0vvR:-KMfDuPsV9gOIOcvYfb5:1801551809) ([raw file](https://github.com/servo/rust-azure/blob/73287e84984aa290f0119c962ba2ffad43dc3f8c/CMakeLists.txt#L60)):*
<details><summary><i>Previously, metajack (Jack Moffitt) wrote…</i></summary>
> I'm not sure what this comment means. Can you describe why pkg_check_modules is insufficient?
</details>
Thanks for fixing the comment, but for this and skia I have the same question of why we need to support older cmake.

---

*[CMakeLists.txt, line 128 \[r5\]](https://reviewable.io:443/reviews/servo/rust-azure/228#-KMRCnlRP66t3J5auxC6:-KMfE6Z2Y18n9MA9lNOK:-1979502749) ([raw file](https://github.com/servo/rust-azure/blob/73287e84984aa290f0119c962ba2ffad43dc3f8c/CMakeLists.txt#L128)):*
<details><summary><i>Previously, metajack (Jack Moffitt) wrote…</i></summary>
> Does the previous EXEC_PROGRAM bit already set cflags? So it should get the right header path. THat should leave only -DMOZ_ENABLE_FREETYPE right?
</details>
You didn't address why we need to do include_directories() here after pkg-config already presumably added this to CFLAGS.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-azure/228)*

**Comment by vvuk** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[CMakeLists.txt, line 60 \[r5\]](https://reviewable.io:443/reviews/servo/rust-azure/228#-KMRCaYnR3Y9NXMX0vvR:-KMzYY4d4zpJT4447Kwb:1253822661) ([raw file](https://github.com/servo/rust-azure/blob/73287e84984aa290f0119c962ba2ffad43dc3f8c/CMakeLists.txt#L60)):*
<details><summary><i>Previously, metajack (Jack Moffitt) wrote…</i></summary>
> Thanks for fixing the comment, but for this and skia I have the same question of why we need to support older cmake.
</details>
Brought in the same comment as I used in Skia, about Ubuntu 14.04 LTS.  It's common enough for people's linux builds that I didn't think it was worth asking everyone to hunt down debs (or upgrade to 16.04).

---

*[CMakeLists.txt, line 128 \[r5\]](https://reviewable.io:443/reviews/servo/rust-azure/228#-KMRCnlRP66t3J5auxC6:-KMzYNHBuTSp0pwd4neP:793591268) ([raw file](https://github.com/servo/rust-azure/blob/73287e84984aa290f0119c962ba2ffad43dc3f8c/CMakeLists.txt#L128)):*
<details><summary><i>Previously, metajack (Jack Moffitt) wrote…</i></summary>
> You didn't address why we need to do include_directories() here after pkg-config already presumably added this to CFLAGS.
</details>
Yep, missed this.  Removed the extra include_directories thing here and consolidated the MSVC/not MSVC branches.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-azure/228)*

**Comment by metajack** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-azure/228#-:-KMzj-RzT2KGWAwejZsi:1236647940)*

**Pull request merged**
