### PR TITLE
skia update

### PR DESCRIPTION
**Pull request by paulrouget**
Depends on https://github.com/servo/skia/pull/149

This will be necessary for https://github.com/servo/servo/pull/19895

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-azure/283)

### CODE REVIEW

**Comment by paulrouget** [comment]
@jdm can you r+ this with @bors-servo? Also, once it lands, can you update crates.io? Thank you :)

**Comment by jdm** [comment]
I've restarted the travis builds that were cancelled.

**Comment by paulrouget** [comment]
@jdm do you know why it says "test failed"? It looks green to me.

**Pull request merged**
