### PR TITLE
Switch to PistonDevelopers freetype-sys

### PR DESCRIPTION
**Pull request by boghison**
Required for servo/servo#3369. Depends on servo/skia#57.

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-azure/183)

### CODE REVIEW

**Comment by jdm** [comment]
Hmm, this one is complicated because our freetype-sys is the actual C source, while PistonDeveloper's freetype-sys is the low-level Rust bindings. @metajack @larsbergstrom We're trying to migrate our dependencies to use https://github.com/PistonDevelopers/freetype-sys/; got any suggestions here?

**Comment by boghison** [comment]
@jdm Perhaps rust-azure should link dynamically?

**Comment by jdm** [comment]
It's not the linking that's a big deal, it's that we're compiling another C library (Azure) that requires including the headers.

**Comment by larsbergstrom** [comment]
Are we even sure we can do this? I assumed we had to build it because there aren't precompiled binaries / distributed versions available for Android, ARM linux, or other embedded platform - @metajack may know more, as the dependency was added before I joined the team :-)

**Comment by jdm** [comment]
Maybe another option is we could rename https://github.com/servo/libfreetype2 to something else than freetype-sys, since the real problem here is that we end up with libraries attempting to link with both ours and PistonDeveloper's.

**Comment by boghison** [comment]
@jdm Ok, but what should we rename it to? And should the changes to skia and libfontconfig be reverted?

**Comment by jdm** [comment]
servo-freetype-sys? We can see what happens without reverting right now.

**Comment by metajack** [comment]
If they are using -sys for bindings, that is a bug. -sys is for system packages.

**Comment by jdm** [comment]
Filed https://github.com/PistonDevelopers/freetype-sys/issues/34.

**Comment by boghison** [comment]
@jdm I have a remark: Cargo alerts that the problem is that the **native library** is being linked to by more than one package, renaming doesn't appear to solve the problem.

**Comment by boghison** [comment]
Unfortunately, servo doesn't build now, because skia and libfontconfig depend on PistonDevelopers freetype-sys, while rust-azure depends on libfreetype2. @jdm Please undo the changes.

**Comment by jdm** [comment]
Go ahead and make PRs to undo them. I don't see a revert button on github.

**Comment by boghison** [comment]
@jdm Done! We still need to discuss how to proceed in order to make it possible to use freetype-rs in servo.

**Pull request closed without merging**
