### PR TITLE
Update servo-freetype-sys req to 4.0.1

### PR DESCRIPTION
**Pull request by vvuk**
... which is https://github.com/servo/libfreetype2/pull/22

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-azure/234)

### CODE REVIEW

**Comment by emilio** [comment]
Can you change the last commit to also include something related with the skia bump? r=me with that.

@bors-servo: try

**Comment by larsbergstrom** [comment]
Failed: https://travis-ci.org/servo/rust-azure/builds/150473404

Error:
```
src/azure_hl.rs:490:54: 490:71 error: no method named `as_azure_int_size` found for type `euclid::size::TypedSize2D<i32, euclid::length::UnknownUnit>` in the current scope

src/azure_hl.rs:490         let mut size = gl_rasterization_context.size.as_azure_int_size();

                                                                         ^~~~~~~~~~~~~~~~~

src/azure_hl.rs:490:54: 490:71 help: items from traits can only be used if the trait is implemented and in scope; the following trait defines an item `as_azure_int_size`, perhaps you need to implement it:

src/azure_hl.rs:490:54: 490:71 help: candidate #1: `azure_hl::AsAzureIntSize`

src/azure_hl.rs:490:54: 490:71 error: no method named `as_azure_int_size` found for type `euclid::size::TypedSize2D<i32, euclid::length::UnknownUnit>` in the current scope

src/azure_hl.rs:490         let mut size = gl_rasterization_context.size.as_azure_int_size();

                                                                         ^~~~~~~~~~~~~~~~~

src/azure_hl.rs:490:54: 490:71 help: items from traits can only be used if the trait is implemented and in scope; the following trait defines an item `as_azure_int_size`, perhaps you need to implement it:

src/azure_hl.rs:490:54: 490:71 help: candidate #1: `azure_hl::AsAzureIntSize`

error: aborting due to previous error

Build failed, waiting for other jobs to finish...

error: aborting due to previous error

error: Could not compile `azure`.
```

**Comment by emilio** [comment]
Seems due to euclid's recent update, I'll try to make a PR to fix it today.

**Comment by nox** [comment]
#236

**Pull request closed without merging**
